feat: add index_by_list command
intezer/analyze-cli pull request #12
Opened 2021-12-22 15:20 UTC by tzlilamar

2021-12-26 11:12 UTC, AlonBucks approved these changes

2021-12-26 11:12 UTC, AlonBucks commented on intezer_analyze_cli/cli.py
> +@main_cli.command('index_by_list', short_help='Send a text file with list of hashes, verdict, family name if malicious')
great job! Just need to update version in __init__.py, add example in README.md

2021-12-26 13:09 UTC, davidt99 commented
Add unittests

2022-01-17 09:52 UTC, davidt99 commented on intezer_analyze_cli/config.py
>          self.analyses_url = 'https://analyze.intezer.com/#/analyses'
remove the hashtag

2022-01-17 09:53 UTC, davidt99 commented on intezer_analyze_cli/commands.py
> +        index.send(wait=True)
We still need to fix this - `send(wait=False)`
After that we need to call `wait_for_completion` for each one

2022-02-10 08:34 UTC, davidt99 commented on intezer_analyze_cli/cli.py
> +@click.argument('index_as', type=click.STRING)
add choice to here so it will validate the input

2022-02-10 08:34 UTC, davidt99 commented on intezer_analyze_cli/cli.py
> +    except NotImplementedError:
after the choice, this should be removed

2022-02-10 08:34 UTC, davidt99 commented on intezer_analyze_cli/commands.py
> +            hashes = [line.rstrip('\n') for line in file.readlines()]
let's strip

2022-02-10 08:34 UTC, davidt99 commented on intezer_analyze_cli/commands.py
> +        with open(path, 'r') as file:
extract if to a method, it's written twice

2022-02-10 08:34 UTC, davidt99 commented on intezer_analyze_cli/commands.py
> +                               label='Indexing files',
"Waiting for indexing to finish"

2022-03-22 08:23 UTC, davidt99 requested changes

2022-03-22 08:23 UTC, davidt99 commented on CHANGES
> + -
add text here

2022-03-22 08:23 UTC, davidt99 commented on intezer_analyze_cli/cli.py
> +@click.option('--index-as', type=click.Choice(['malicious', 'trusted'], case_sensitive=False))
i think we need it to be case sensitive

2022-03-22 08:23 UTC, davidt99 commented on intezer_analyze_cli/cli.py
> +@click.option('--index-as', type=click.Choice(['malicious', 'trusted'], case_sensitive=False))
can you do this to the other index endpoint?

2022-04-20 10:29 UTC, davidt99 approved these changes

2022-04-20 10:31 UTC, merged